### ISSUE TITLE
Depends on Rails 5?

### ISSUE THREAD

**Issue by jonathanhoskin** [kddeisz/iseq-rails-tools#5]
Hi. I'm running on Rails 4.2.x. Just wondering if this gem's dependency on Rails 5.x is due to specifically _needing_ Rails 5.x, or could the `.gemspec` be relaxed a bit?

**Comment by kddeisz** [comment]
No reason, that was just what was generated by default. I just released version 0.0.8 which relaxed the gemspec. Let me know how it works out!

**Comment by jonathanhoskin** [comment]
Perfect. Thanks @kddeisz !
